# Generated by Django 4.0.10 on 2023-06-08 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='uuid',
        ),
    ]
