version: "3.9"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-&guosvv-8at7e9-_e1&eezsb57hp@vrx^(3$$^vwv3aw(yj^n!x"
      - "DJANGO_DEBUG=True"
      - 'DJANGO_EMAIL_HOST=smtp.gmail.com'
      - 'DJANGO_EMAIL_HOST_USER=vetrof@gmail.com'
      - 'DJANGO_EMAIL_HOST_PASSWORD=immptejvybrlxqhw'
      - 'DJANGO_EMAIL_PORT=587'
      - 'DJANGO_EMAIL_USE_TLS=True'
      - 'DJANGO_EMAIL_USE_SSL=False'
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:

